sudo: false

language: scala
scala:
  - 2.13.0

dist: xenial
services:
  - xvfb

jdk:
  - openjdk11

install: true

script:
  - java -version
  - sbt test

#branches:
#  only:
#    - master
#    - stable

notifications:
  email:
    - scalafx-build@googlegroups.com

