sudo: false

language: scala
scala:
- 2.10.7
- 2.11.12
- 2.12.8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - openjdk11
  
install: true

script:
  - java -version
  - sbt test

branches:
  only:
  - SFX-11
  - SFX-11-stable

notifications:
  email:
    - scalafx-build@googlegroups.com

