sudo: false

language: scala
scala:
- 2.10.7
- 2.11.12
- 2.12.8

dist: xenial
services:
  - xvfb

jdk:
  - openjdk11
  - openjdk12

install: true

script:
  - java -version
  - sbt test

branches:
  only:
    - master
    - stable

notifications:
  email:
    - scalafx-build@googlegroups.com

