sudo: false

language: scala
scala:
  - 2.13.1
  - 2.12.10
  - 2.11.12
  - 2.10.7

dist: xenial
services:
  - xvfb

jdk:
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - openjdk11
  - openjdk12
  - openjdk13

install: true

script:
  - java -version
  - sbt test

