sudo: false

language: scala
scala:
- 2.10.7
- 2.11.12
- 2.12.8

dist: xenial
services:
  - xvfb

jdk:
  - oraclejdk8
  
install: true

script:
  - java -version
  - sbt test

branches:
  only:
    - SFX-8
    - SFX-8-stable

notifications:
  email:
    - scalafx-build@googlegroups.com

# Work around for default old version of Java provided by Travis CI
addons:
  apt:
    packages:
      - oracle-java8-installer
